name: pygdal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - gdal=3.4.2
  
  - pip:
    - absl-py==1.0.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cycler==0.11.0
    - flask==2.1.2
    - fonttools==4.32.0
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - grpcio==1.46.0
    - idna==3.3
    - itsdangerous==2.1.2
    - joblib==1.1.0
    - kiwisolver==1.4.2
    - markdown==3.3.7
    - matplotlib==3.5.1
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - pandas==1.3.5
    - pillow==9.1.0
    - protobuf==3.20.1
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - sklearn==0.0
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - thop==0.0.31-2005241907
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
    - urllib3==1.26.9
    - werkzeug==2.1.2


